export const OFFICIAL_ICONS = {
    accounting: "/icons/accounting.png",
    badge: "/icons/badge.png",
    bank: "/icons/bank.png",
    bill: "/icons/bill.png",
    briefcase: "/icons/briefcase.png",
    briefcaseAlt: "/icons/briefcase-alt.png",
    calculator: "/icons/calculator.png",
    calculatorAlt: "/icons/calculator-alt.png",
    calendar: "/icons/calendar.png",
    calendarAlt: "/icons/calendar-alt.png",
    chat: "/icons/chat.png",
    creditCard: "/icons/credit-card.png",
    ecommerce: "/icons/ecommerce.png",
    economy: "/icons/economy.png",
    edc: "/icons/edc.png",
    edcAlt: "/icons/edc-alt.png",
    invoice: "/icons/invoice.png",
    needAssessment: "/icons/need-assessment.png",
    priceTag: "/icons/price-tag.png",
    rating: "/icons/rating.png",
    saleTime: "/icons/sale-time.png",
    sales: "/icons/sales.png",
    shoppingBag: "/icons/shopping-bag.png",
    shoppingCart: "/icons/shopping-cart.png",
    startup: "/icons/startup.png",
    stock: "/icons/stock.png",
    taxes: "/icons/taxes.png",
    voucher: "/icons/voucher.png",
    website: "/icons/website.png",
    worldwide: "/icons/worldwide.png",
} as const;

export type OfficialIconKey = keyof typeof OFFICIAL_ICONS;
